#! /bin/sh

chosen=$(printf "Apagar\nReiniciar\nCerrar" | rofi -dmenu -i)

case "$chosen" in
  "Apagar") systemctl poweroff ;;
  "Reiniciar") systemctl reboot ;;
  "Cerrar") i3-msg exit ;;
  *) exit 1 ;;
esac

