#! /bin/sh

chosen=$(printf "Apagar\nReiniciar\nCerrarSesión" | rofi -dmenu -i)

case "$chosen" in
  "Apagar") systemctl poweroff ;;
  "Reiniciar") systemctl reboot ;;
  "CerrarSesión") kill -9 -1 ;;
  *) exit 1 ;;
esac

