#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X
xrandr -s 1920x1080
#feh --bg-scale ~/Imágenes/fondos/fondo1.png
nitrogen --restore
killall -q nm-applet
nm-applet
~/.config/polybar/launch.sh

bspc config border_width        1
bspc config window_gap          1

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a firefox  desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
